# training data
data_dir: /media/siat04/硬盘/data/DeepLesion1.0/Images_png/Images_png/
# model
model_name: Unet
schedule_sampler: "uniform"
image_size: 512
in_channels: 1
num_channels: 128
num_head_channels: 64
num_res_blocks: 2
channel_mult: '1,1,2,2,4' # '1,1,2,2'
class_cond: False
patch_size: 4
learn_sigma: True
use_scale_shift_norm: True
use_new_attention_order: True
# diffusion
diffusion_steps: 1000
noise_schedule: linear
# train
lr: 1.0e-4
weight_decay: 0.0
lr_anneal_steps: 0
microbatch: -1
ema_rate: "0.9999"
log_interval: 10
save_interval: 10000
resume_checkpoint: ""
use_fp16: True
fp16_scale_growth: 1.0e-3
weight_schedule: "sqrt_snr"
# sample
model_path: /media/siat04/硬盘/codes/PatchDiffusion-Pytorch-main/experiments/openai-2023-07-24-17-00-36-204065/model150000.pt
use_ddim: False
clip_denoised: True
batch_size: 1
num_samples: 1
timestep_respacing: [10, 10, 10, 10, 10, 10, 10, 10, 10, 10]
# MAR test
a: 0.4 # \delta(t) = (a-1)e^{-n\frac{t}{T}}+1
n: 4 # \delta(t) = (a-1)e^{-n\frac{t}{T}}+1
delta_y: 0.8 # \mathcal{M}_y = \mathcal{M}(\delta_y).
save_dir: 'results/DuDoDp-MAR' # Path of MAR results
data_path: './test_data/SynDeepLesion' # Path of test data
inner_dir: 'test_640geo/' # be 'apdcephfs/share_1290796/hazelhwang/mardataset/test_640geo/' for data from https://github.com/hongwang01/SynDeepLesion
# root 
# ├── test_640geo_dir.txt 
# ├── testmask.npy
# └── inner_dir
#          ├── ...
#          └── patient
#               ├── ...
#               └── slice
#                     ├── 0.h5
#                     ├── ...
#                     └── gt.h5
num_test_image: 1 # num of test image, 200 for all test images
num_test_mask: 10 # number of test masks